### ISSUE TITLE
RequestId is no longer generated/added to response headers in version 1.6.0

### ISSUE THREAD

**Issue by PS99999** [arcus-azure/arcus.webapi#365]
Hi
We have updated several Arcus packages in our API project, and we have ceased to receive back the RequestId in the response headers. 
Among the updated packages is the Arcus.Webapi.Logging 1.6.0. which I believe it might be the one directly related to the issue.

We have tried to explicitly add the header configuration to the httpCorrelation on the API Program class. By the way we have noticed that the properties are marked as obsolete.
But it still does not generate it. 

![image](https://user-images.githubusercontent.com/91678944/180779031-ba268af7-3cee-4f3d-8ada-a7a6ee22879b.png)

Is this an expected behavior of the new version. Are we missing any additional configuration/logic in order for the RequestId be generated and included in the response headers?
If I just revert the Arcus.Webapi.Logging to 1.5.0, it will generate back the requestId (among other headers), but I get some conflict issues with other Arcus packages also upgraded (e.g.: Arcus.Observability.Telemetry.AspNetCore). We could also downgrade these packages, but we would like to avoid that if possible.

Please let me know if we need to provide any more information to reply to this issue.

Thank you.

**Comment by stijnmoreels** [comment]
Hi! Thx for reaching out.

It is true that we have changed the HTTP correlation here. The previous versions where not fully compatible with the HTTP correlation standard, which we made sure is fixed in v1.6.
The parent operation ID is now called the `Request-Id` and will be available when such a value is present. The operation ID is now also no longer part of the response, as it's only used within the receiver API and not in the sender API, exposing the operation ID here is not needed for a service-to-service correlation setup.

For a full and detailed explanation of the Arcus HTTP correlation setup, you can look into our [feature documentation](https://webapi.arcus-azure.net/features/correlation) where we discuss each step in a multi-application setup.

**Comment by gverstraete** [comment]
Hello,

I don't fully understand yet. 
You still have the possibility to generate an id, and a setting to include it in the response in the `AddHttpCorrelation`. Why is it not in the response if we configure it like that?

I'd prefer to always have a id identifying the request as a response for easy troubleshooting from third-parties.

Thanks for the reply!

**Comment by stijnmoreels** [comment]
> I don't fully understand yet. You still have the possibility to generate an id, and a setting to include it in the response in the `AddHttpCorrelation`. Why is it not in the response if we configure it like that?
> 
> I'd prefer to always have a id identifying the request as a response for easy troubleshooting from third-parties.
> 
> Thanks for the reply!

Ah, ok, this is an additional feature, then, as we previously miss-used the operation ID, and were migrating away from it (you'll see warnings if you try to add it to the response). But I see your point. It could be useful to in some cases to expose the ID to the sender. We may want to use a different name (was default `X-Operation-ID` I think before we jumped to `Request-Id`), to avoid conflicting with the parent ID called `RequestId`.

I'll sum up:
- [ ] Re-activate operation ID to response
- [ ] Change default operation ID response header with `X-Operation-ID`

Would that be ok? I can take this up and release a fix version of this.

**Comment by gverstraete** [comment]
Agree!

if we can override the name of `X-Operation-ID` it would be perfect (But I think we set this today with the properties)

**Comment by stijnmoreels** [comment]
Fixed in #367, feel free to create a new issue for additional help.
Thx!

**Comment by PS99999** [comment]
Hi
Thank you very much for the help and quick change! 
We will try out asap the new preview package, and then wait for the next release.
